# Generated by Django 4.2.7 on 2023-12-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0002_alter_post_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Chanel',
        ),
        migrations.AlterModelOptions(
            name='chanel',
            options={'verbose_name': 'Телеграм канал', 'verbose_name_plural': 'Телеграм каналы'},
        ),
        migrations.RenameField(
            model_name='chanel',
            old_name='group_chat_id',
            new_name='chanel_chat_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='chanel',
        ),
    ]
