# Generated by Django 4.2.7 on 2023-12-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0003_rename_group_chanel_alter_chanel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='IATA код города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_trips', to='trip_admin_app.city', verbose_name='Куда')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_trips', to='trip_admin_app.city', verbose_name='Откуда')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.AlterField(
            model_name='chanel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название канала телеграм'),
        ),
        migrations.CreateModel(
            name='TicketsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_admin_app.chanel', verbose_name='Для канала')),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_admin_app.destination', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Подборка билетов',
                'verbose_name_plural': 'Подборки билетов',
            },
        ),
    ]
