# Generated by Django 4.2.7 on 2023-12-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0005_country_city_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='code',
        ),
    ]
