# Generated by Django 4.2.7 on 2023-12-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0006_alter_country_options_rename_name_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trip_admin_app.country'),
            preserve_default=False,
        ),
    ]
