# Generated by Django 4.2.7 on 2023-12-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0007_destination_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.AddField(
            model_name='destination',
            name='chanel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_chanel', to='trip_admin_app.chanel', verbose_name='Для канала'),
            preserve_default=False,
        ),
    ]
