# Generated by Django 4.2.7 on 2023-12-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0011_remove_ticketslist_destinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tickets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trip_admin_app.ticketslist', verbose_name='Подборка билетов'),
            preserve_default=False,
        ),
    ]
