# Generated by Django 4.2.7 on 2023-12-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0012_post_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_admin_app.destination', verbose_name='Подборка билетов'),
        ),
        migrations.DeleteModel(
            name='TicketsList',
        ),
    ]
