# Generated by Django 4.2.7 on 2023-12-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0013_alter_post_tickets_delete_ticketslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='chanel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tickets',
        ),
        migrations.AddField(
            model_name='destination',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_post', to='trip_admin_app.post', verbose_name='К посту'),
            preserve_default=False,
        ),
    ]
