# Generated by Django 4.2.7 on 2023-12-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0015_post_last_viewed_destination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_viewed_destination_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Последнее публикованное направление(id)'),
        ),
    ]
