# Generated by Django 4.2.7 on 2023-12-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0017_remove_post_last_viewed_destination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='count_of_destinations_in_post',
            field=models.IntegerField(default=5, verbose_name='Направлений полета в посте'),
        ),
    ]
