# Generated by Django 4.2.7 on 2023-12-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0018_destination_count_of_destinations_in_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='count_of_destinations_in_post',
        ),
        migrations.AddField(
            model_name='post',
            name='count_of_directions_in_post',
            field=models.IntegerField(default=5, verbose_name='Направлений полета в посте'),
        ),
    ]
