# Generated by Django 4.2.7 on 2023-12-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0020_alter_post_count_of_directions_in_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_pictures/', verbose_name='Изображение поста'),
        ),
    ]
