# Generated by Django 5.0 on 2024-01-06 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0023_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='return_tickets',
            field=models.BooleanField(default=False, verbose_name='Билеты обратно'),
        ),
        migrations.AddField(
            model_name='post',
            name='tickets_in_direction',
            field=models.PositiveIntegerField(default=1, verbose_name='Билетов для каждого направления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chanel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_admin_app.chanel', verbose_name='Телеграм канал'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
