# Generated by Django 5.0 on 2024-01-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0024_post_return_tickets_post_tickets_in_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст (необъязательно)'),
        ),
    ]
