# Generated by Django 5.0 on 2024-01-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0025_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tickets_in_direction',
            field=models.PositiveIntegerField(default=5, verbose_name='Билетов для каждого направления'),
        ),
    ]
