# Generated by Django 5.0 on 2024-01-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0026_alter_post_tickets_in_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tickets_in_direction',
            new_name='count_of_tickets_in_direction',
        ),
    ]
