# Generated by Django 5.0 on 2024-01-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0027_rename_tickets_in_direction_post_count_of_tickets_in_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_of_directions_in_post',
        ),
    ]
