# Generated by Django 5.0 on 2024-01-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0028_remove_post_count_of_directions_in_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='text_after',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст вконце (необъязательно)'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_before',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст вначале (необъязательно)'),
        ),
    ]
