# Generated by Django 5.0 on 2024-01-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0031_alter_post_text_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_after',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Текст вконце (необъязательно)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_before',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Текст вначале (необъязательно)'),
        ),
    ]
