# Generated by Django 5.0 on 2024-02-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0033_alter_post_text_after_alter_post_text_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_price_of_tickets',
            field=models.IntegerField(default=8000, verbose_name='Максимально допустимая цена билета'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='post_pictures/', verbose_name='Изображение поста (отобразится если недоступна генерация через ИИ)'),
        ),
    ]
