# Generated by Django 4.2.7 on 2024-02-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_admin_app', '0033_alter_post_text_after_alter_post_text_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст ошибки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='max_price_of_tickets',
            field=models.IntegerField(default=8000, verbose_name='Максимально допустимая цена билета'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='post_pictures/', verbose_name='Изображение поста (отобразится если недоступна генерация через ИИ)'),
        ),
    ]
